enhance build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,15 @@
+#!/bin/bash
+
+elm-test
+test_result=$?
+if [ $test_result -gt 0 ] ; then
+  echo "Exiting $test_result because tests failed"
+  exit $test_result
+fi
+
+echo "Cleaning target..."
 rm -rf target/*
+echo "Resources..."
 cp -r resources/* target
+echo "Compiling..."
 elm make --output target/elm.js src/Main.elm
